name: Run tests
on:
  push:
    branches:
      - 'main'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install -e .
      - name: Run pytest
        run: python -m pytest
